[package]
    edition = "2021"
    name    = "header_lookup_example"
    version = "0.1.0"

[dependencies]
    anyhow            = "1.0"
    c_header_analyzer = { path = "../c_header_analyzer" }
    library_db        = { path = "../library_db" }
    serde_json        = "1.0"
